DROP TABLE IF EXISTS RESTAURANTS;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS ITEMS;

CREATE TABLE LOCATION (
  ID INT PRIMARY KEY,
  LATITUDE VARCHAR(250) NOT NULL,
  LONGITUDE VARCHAR(250),
  ADDRESS VARCHAR(250),
  ZIP_CODE VARCHAR(250)
  );

CREATE TABLE RESTAURANTS (
  RES_ID INT PRIMARY KEY,
  BUDGET FLOAT,
  MIN_ORDER INT,
  NAME VARCHAR(250) NOT NULL,
  RATING FLOAT,
  RATING_TEXT VARCHAR(250),
  THUMB VARCHAR(250),
  IMAGE_URL VARCHAR(250),
  WAIT_TIME VARCHAR(250),
  LOCATION_ID int FOREIGN KEY REFERENCES LOCATION(ID)
  );
  
  CREATE TABLE ITEMS (
  ID INT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  RES_ID int FOREIGN KEY REFERENCES RESTAURANTS(RES_ID)
  VEG_FLAG BOOLEAN,
  TYPE VARCHAR(250),
  PRICE INT NOT NULL
   );