version: '2.1'
services:
  ordermyfood:
    image: com.mindtree.omf/microservice-docker-ordermyfood:0.0.1-SNAPSHOT
    ports:
      - 80:7001
    depends_on:
      sqlserver:
        condition: service_started
  sqlserver:
    image: mysql:latest
    container_name: sqlserver
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=my-pass
      - MYSQL_DATABASE=OMF
  configserver:
    image: com.mindtree.omf/microservice-docker-configserver:0.0.1-SNAPSHOT
    depends_on:
      ordermyfood:
        condition: service_started
    volumes:
      - ./config-data:/var/config-data
    environment:
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://ordermyfood:7001/eureka
         -Dspring.cloud.config.server.native.searchLocations=/var/config-data
  searchservice:
    image: com.mindtree.omf/microservice-docker-searchservice:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://ordermyfood:7001/eureka
    depends_on:
      configserver:
        condition: service_started
      ordermyfood:
        condition: service_started
