version: '3'
services:
  ordermyfood:
    image: com.mindtree.omf/microservice-docker-ordermyfood:0.0.1-SNAPSHOT
    container_name: ordermyfood
    ports:
      - 7001:7001
    depends_on:
      - sqlserver
  sqlserver:
    image: mysql:latest
    container_name: sqlserver
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=my-pass
      - MYSQL_DATABASE=OMF
  configserver:
    image: com.mindtree.omf/microservice-docker-configserver:0.0.1-SNAPSHOT
    depends_on:
      - ordermyfood
    ports:
      - 7005:7005
    volumes:
      - ./config-data:/tmp
    environment:
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://ordermyfood:7001/eureka