version: '3'
services:
  ordermyfood:
    image: com.mindtree.omf/microservice-docker-ordermyfood:0.0.1-SNAPSHOT
    ports:
      - 7001:7001
    expose:
      - 3306
    depends_on:
      - sqlserver
  sqlserver:
    image: mysql:latest
    container_name: sqlserver
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=OMF
